name: Rest Assured Test Suite

on: workflow_dispatch

jobs:
  rest_assured_build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: check workspace
        run: |
          echo "Your current workspace is ${{ github.workspace }}"
          echo "The name of your branch is ${{ github.ref }} and name of repository  is ${{ github.repository }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: checkout to repo
        uses: actions/checkout@v4

      - name: run build package
        run: |
          mvn clean package

      - name: run tests suite
        run: |
          mvn clean test